Change time-related flags to durations
kubernetes/git-sync pull request #299
Opened 2020-10-31 07:38 UTC by thockin

Builds on #298 

Add '--period' to replace '--wait', which is now obsolete.
    
Add '--sync-timeout' to replace '--timeout', which is now obsolete.
    
Both of these new flags take a Go-style time string, rather than a bare
number. For example "1s" for 1 second or "1m" for one minute.
    
The old flags have been kept and will take precedence if specified.

xref #297

2020-11-05 11:03 UTC, stp-ip requested changes
small nit

/approve

2020-11-05 11:03 UTC, stp-ip commented on cmd/git-sync/main.go
> +            extend the effective period between syncs attempts.
```suggestion
            extend the effective period between sync attempts.
```

2020-11-06 00:45 UTC, thockin commented on cmd/git-sync/main.go
> +            extend the effective period between syncs attempts.
ACK

2020-11-06 00:47 UTC, thockin commented
Fixed, rebased and repushed.  PTAL

2020-11-06 08:57 UTC, stp-ip commented
/lgtm

2020-11-06 08:58 UTC, merged